Replace braces by parens when constructing IrregularType in macro calls
Macro calls don't respect curly braces, for example:

    EXPECT_REGULAR(
      IrregularType{ std::vector<int>(1) },
      IrregularType{ std::vector<int>{1, 2, 3} });

Would cause compilation errors:
> warning C4002: too many arguments for function-like macro invocation 'EXPECT_REGULAR'
> error C3329: syntax error: expected '}' not ')'

This commit replaces braces by parentheses, in those tests where `IrregularType` has an explicit user-defined constructor.